### ISSUE TITLE
Edit Chapter iab on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#143]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Liz

Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
good | Figure 4 and Table 2 are on the same page | Table 2 is on the same page as figure 4 (I think because when I float the table, it moves it to the end of the chapter), **Table 1 is a placeholder that needs fixing** | none | good; insert newpages to fix some spacing issues | added one list, other lists look good | - moved several websites to footnotes (although I kept the websites in people's bios)- two websites need last access dates (Rheinisch-westfalisches institut fur wirschaftsforschung 2016 and bundesminsterium fur arbeit und soziales 2017) and CHristina Boll 2015 doesn't have a DOI | yes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Updated table 1

There isn't a good way to get figure 4 and table 2 off of the same page.

Updated Christina Boll website and two missing URLs noted in the content change.

Updated web version to have same list as in latex version (list starting with *Research topic* in "Safe Projects")

Redoing Liz's website footnote conversions (instead of the entire sentence into a footnote, just put the URL into a footnote).

**Comment by jimhshen** [comment]
Fixed image/table positioning
Finalized layout
Updated footnotes
Added last accessed footnotes to both web and PDF version

**Comment by jimhshen** [comment]
Also added cross-reference links for both PDF and HTML (e.g. "see section on Safe Data" is now hyperlinked appropriately)

**Comment by jimhshen** [comment]
Ready for author final proof.

**Comment by jimhshen** [comment]
Your left the following comment in the URLs sheet for http://www.gesetze-im-internet.de/sgb_3/__282.html: "Move the URL to a citation upon usage (next sentence), similar to the IRB chapter for English citations of laws"

I added a zotero entry currently with a citekey of larsfixthis - can you take a look at it? I can't read German so I'm not sure I'm doing the citation correctly.

**Comment by larsvilhuber** [comment]
fixed. citation key to use in the text: @sgb282.3

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
