### ISSUE TITLE
Edit Chapter olda on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#144]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Mike


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content
-- | -- | -- | -- | -- | -- | --
good | good | good | none | good | good (two very short ones) | new page for the authors section, resized image. added some last access dates | yes

**Comment by jimhshen** [comment]
Added citation for 20 CFR Part 603 (was previously plain text).

Added access dates to URLs, including within tables.

Updated tables required updating formatting.

Bibliography package seems to be doing something weird with rendering citations (not chapter speciifc latex issue).

hawley203 and hawley2003a citations need URLs, not publicly available.

Otherwise ready for author proof.

**Comment by jimhshen** [comment]
Questions for Hawley:
Capitalization and plurals of of policy committee(s) and data stewards in "Formal Governance Process"
Capitalization of "the investigator" in making data usable for research"
Is there something missing in "The initial idea for the data system emerged in 2007 out of a partnership
between faculty at the university"
