### ISSUE TITLE
Edit Chapter pcri on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#146]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
How does this look for replacing the pie chart?

![pcrifigurea2-replacementtest](https://user-images.githubusercontent.com/20117905/97363681-56b8e780-1879-11eb-9f8f-4e1793d7e9aa.png)

**Comment by larsvilhuber** [comment]
Better. I'm going to assume the font will be too small. It may be more useful to lump the very small slices into an "other category", anything less than 5%. Finally, I would put the label for us inside the pie, rather than underneath it, which saves space.

Are you doing this or the PCRI folks?

--
Lars Vilhuber
on mobile device

________________________________

**Comment by jimhshen** [comment]
I was doing it in plotly in R, trying to duplicate the original layout but updating the colors and getting rid of the legend.

Font size: can be adjusted to be bigger relative to the chart
Lumping the slices: would have to ask the authors for permission
Putting the label for US inside the pie: looks like there's [a solution](https://community.plotly.com/t/text-position-inside-for-label-and-outside-for-value-pie-chart/8952/3) involving laying two pie charts on top of each other.

**Comment by jimhshen** [comment]
PCRI replied that they can't do the images, so I generated the other two replacement ones. If these look ok I'll update the PCRI branch with these files.

![pcrifigurea2new](https://user-images.githubusercontent.com/20117905/98022737-faebe280-1dd3-11eb-899d-415c17c057c6.png)

![pcrifigure1new](https://user-images.githubusercontent.com/20117905/98022748-fd4e3c80-1dd3-11eb-8a77-cb07190a80d3.png)

![pcrifigurea3](https://user-images.githubusercontent.com/20117905/98022796-0c34ef00-1dd4-11eb-93e8-bde41bfff4ac.png)

**Comment by larsvilhuber** [comment]
Not great grey-scale-wise, but should do. (see attached GS conversion)

I would remove the counts (leave %), and in the topmost, try and move labels into the pie pieces.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by jimhshen** [comment]
I don't think you attached the conversion. I'm using the same colorbrewer scheme as the other images we generated, but I doubt there's any that will fit 5-9 categories nicely. I can move the colors around the pie charts so similar colors are not next to each other.

**Comment by jimhshen** [comment]
Editor: Jack


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content
-- | -- | -- | -- | -- | -- | --
good | -Removed superfluous capitalization and added periods to appendix figures-Caption for figure 2 was the same as caption for figure 1 (and didn't describe figure 2); added in the description of the figure from RMD-Resized appendix figure 3 to be about the same size as appendix figure 2 | -Changed text size in appendix tables 1 & 2 so that they would fit on the page-Corrected typo, changed text size and removed unused column from code for appendix table 3 | none | good | -Switched the second list to bullets to match the style of the other two lists (there didn't seem to be a strong argument for numbers here) | - Working paper "Globalization of alternative investments." doesn't have either DOI or URL in citations-Changed hyperlinks in text to footnotes

**Comment by jimhshen** [comment]
Reformatted appendix to include link for online appendix B and C in Latex

Edited captions for figures and tables (did Jack's changes get lost?) and footnotes to "Notes" instead of "Note"

Changed Rmd list to numbers

Flagged missing URLs in Zotero

Added access dates for URLs

Modified appendix hyperlink in Rmd for PCRI and all other chapters so hyperlinks printed in the Handbook will be consistent instead of relying on bookdown autogenerated URLs

Updated appendix bar graph (manually edited labels as we do not have the raw data) to be more readable

**Comment by jimhshen** [comment]
Quote from section 3 of ECB changed from [November 2016 draft language ](http://prod2.hoganlovells.com/en/blogs/the-buyout-board/lending-cap-to-be-imposed-by-ecb-will-the-new-ecb-guidance-adversely-affect-leveraged-transactions#_ftn1) to current language in 2017-05 document cited in chapter.
