### ISSUE TITLE
Edit Chapter cct on Overleaf

### ISSUE THREAD

**Issue by larsvilhuber** [admindatahandbook/book#149]
Overleaf is at https://www.overleaf.com/project/5f9342e1339ad00001993c32 . Instructions are at https://docs.google.com/document/d/1N1UXFCHk_gRg5LlaIP-h0yPcL7uCKCR0u61qutG4DaQ/edit#

**Comment by jimhshen** [comment]
Editor: Liz


Titles | Figures | Tables | Breakout Boxes | General Formatting | Lists | Content | Completed
-- | -- | -- | -- | -- | -- | -- | --
good | rotated figure and put it on its own page (using \begin{figure}[p] instead of \begin{figure}[t]; caption is not sideways with the figure though | when I float the table, it puts it at the end of the chapter for some reason | none |   | good (three lists) | - suggestion to use a different heading for the "importance = x, cost=x" in section 5 (no changes made though)- three citations need a last access date: Giles 2020, Republic of South Africa spatial data infrastructure (2003), and Republic of South Africa protection of personal information (2013)- moved links to footnotes (except for the ones in people's bios) | yes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by jimhshen** [comment]
Rotated figure using sidwaysfigure to get the caption to rotate.

Table float fixed.

Added access dates to flagged citations

Added access dates to URLs

Updated online appendix text

**Comment by jimhshen** [comment]
Ask if city research framework is available yet.
