### ISSUE TITLE
Updated layout

### ISSUE THREAD

**Issue by jimhshen** [admindatahandbook/book#30]
Based on the discussion and comments at one of the previous meetings and over email, I updated the layout of the book. Let me know if you want any changes. Anja had a preference for dropping the stuff about the case study template from the final published version, but I kept it in for now.

https://jimhshen.github.io/admindatahandbook/

**Comment by larsvilhuber** [comment]
Some of the case study template language should be dropped (formatting, Word documents,...). We won't do it like that in the next round, if there is a next round. the case study template itself should be there, since that helps people format submissions in the future - I didn't see , but I'll have a more precise look.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
